name: Build AppImage

on:
  release:
    release:
      types: [published]
    branches:
      - main
    paths:
      - 'app.py'
      - 'build.spec'
      - 'OpenMic.desktop'
      - 'requirements.txt'
      - 'templates/**'
      - 'static/**'
      - '.github/workflows/build-appimage.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Pywebview Dependencies
        run: |
          sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.1
          
      - name: Checkout Fork Repository
        uses: actions/checkout@v4

      - name: PyInstaller Linux
        uses: JackMcKew/pyinstaller-action-linux@0.1.4
        with:
          path: .
          
      # - name: Build AppImage
      #   uses: AppImageCrafters/build-appimage@master
      #   with:
      #     recipe: "./AppImageBuilder.yml"
      #   env:
      #     UPDATE_INFO: gh-releases-zsync|AppImageCrafters|openmic|latest|*x86_64.AppImage.zsync

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AppImage
