on: [push]
jobs:
  pyinstaller-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'OpenMic'
