on: [push]
jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install pywebview[qt]
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'OpenMic'
