name: Build AppImage

on:
  release:
    release:
      types: [published]
    branches:
      - main
    paths:
      - 'app.py'
      - 'build.spec'
      - 'OpenMic.desktop'
      - 'requirements.txt'
      - 'templates/**'
      - 'static/**'
      - '.github/workflows/build-appimage.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Pywebview Dependencies
        run: |
          sudo apt update
          sudo apt install python3-webview libgirepository1.0-dev
          
      - name: Checkout Fork Repository
        uses: actions/checkout@v4

      - name: ls
        run: ls .

      - name: Run Pyinstaller
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          pyinstaller_ver: '==5.13.2'
          spec: './build.spec'
          requirements: './requirements.txt'
          upload_exe_with_name: 'OpenMic'
          options: --onefile, --name "OpenMic", --windowed, 
          
      # - name: Build AppImage
      #   uses: AppImageCrafters/build-appimage@master
      #   with:
      #     recipe: "./AppImageBuilder.yml"
      #   env:
      #     UPDATE_INFO: gh-releases-zsync|AppImageCrafters|openmic|latest|*x86_64.AppImage.zsync
