name: Build AppImage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-0 libgtk-3-0 libwebkit2gtk-4.0-37 libfuse2 appstream

    - name: Install build tools
      run: sudo apt-get install -y build-essential

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller build.spec  # Replace "your_script.py" with the entry point of your Python application

    - name: Create AppDir
      run: |
        mkdir -p AppDir
        cp dist/OpenMic AppDir/
        cp OpenMic.desktop AppDir/
        cp static/icons/logo.png AppDir/openmic.png

    - name: Download linuxdeploy
      run: |
        wget -O linuxdeploy https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy

    - name: Create AppImage
      run: |
        ./linuxdeploy --appdir=AppDir --output appimage

    - name: Upload AppImage as artifact
      uses: actions/upload-artifact@v2
      with:
        name: OpenMic
        path: $GITHUB_WORKSPACE/OpenMic-x86_64.AppImage
