on: [push]
jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-webkit2-4.1
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'OpenMic'
